// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnsPyY-oJ0sCxtG6cIh5KRsQfs0ip5JM',
    appId: '1:224114515547:web:39991d7b00dd63f653e97e',
    messagingSenderId: '224114515547',
    projectId: 'project-1b9ab',
    authDomain: 'project-1b9ab.firebaseapp.com',
    databaseURL: 'https://project-1b9ab-default-rtdb.firebaseio.com',
    storageBucket: 'project-1b9ab.appspot.com',
    measurementId: 'G-FRK7FMVBR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM91KardbEFLFSlMXS5PGny4ANb-ZhX4k',
    appId: '1:224114515547:android:c6d85fa6df68eb9953e97e',
    messagingSenderId: '224114515547',
    projectId: 'project-1b9ab',
    databaseURL: 'https://project-1b9ab-default-rtdb.firebaseio.com',
    storageBucket: 'project-1b9ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPWChqIZ8y19sDdbNyMGvucyZqwwbez8',
    appId: '1:224114515547:ios:d63b1a14b0bac26953e97e',
    messagingSenderId: '224114515547',
    projectId: 'project-1b9ab',
    databaseURL: 'https://project-1b9ab-default-rtdb.firebaseio.com',
    storageBucket: 'project-1b9ab.appspot.com',
    iosBundleId: 'com.example.projectFoodFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANPWChqIZ8y19sDdbNyMGvucyZqwwbez8',
    appId: '1:224114515547:ios:b5a96ecdc25b566053e97e',
    messagingSenderId: '224114515547',
    projectId: 'project-1b9ab',
    databaseURL: 'https://project-1b9ab-default-rtdb.firebaseio.com',
    storageBucket: 'project-1b9ab.appspot.com',
    iosBundleId: 'com.example.projectFoodFit.RunnerTests',
  );
}
